# go2rtc configuration template
log:
  level: info

api:
  listen: ":1984"

rtsp:
  listen: ":8554"

webrtc:
  listen: ":8555"
  candidates:
    - stun:stun.l.google.com:19302
    - stun:stun1.l.google.com:19302

ffmpeg:
  bin: "ffmpeg"

streams: {}
